// <auto-generated />
using System;
using Ai_Fitness_Coach.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ai_Fitness_Coach.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260428194759_exercises")]
    partial class exercises
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ai_Fitness_Coach.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TargetMuscles")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Equipment = "barbell",
                            ExerciseType = "chest",
                            ImageUrl = "https://i.pinimg.com/736x/c6/4e/a9/c64ea9a4aeec242e709e0ee4f0e06c2e.jpg",
                            IsDeleted = false,
                            Name = "Bench Press",
                            TargetMuscles = "chest",
                            VideoUrl = "https://youtube.com/shorts/0cXAp6WhSj4?si=j9wOwxSGDUij01_S"
                        },
                        new
                        {
                            Id = 2,
                            Equipment = "dumbbell",
                            ExerciseType = "chest",
                            ImageUrl = "https://i.pinimg.com/736x/9b/48/27/9b48276aeba128d50f17087c7a24434e.jpg",
                            IsDeleted = false,
                            Name = "Incline Dumbbell Press",
                            TargetMuscles = "upper_chest",
                            VideoUrl = "https://youtu.be/IP4oeKh1Sd4?si=CUqBXNoL7jCe5L0s"
                        },
                        new
                        {
                            Id = 3,
                            Equipment = "barbell",
                            ExerciseType = "chest",
                            ImageUrl = "https://i.pinimg.com/736x/3a/f5/84/3af584e0bea6ed711905021002ebedcc.jpg",
                            IsDeleted = false,
                            Name = "Decline Press",
                            TargetMuscles = "lower_chest",
                            VideoUrl = "https://youtu.be/LfyQBUKR8SE?si=7okiJuu9tLOu8sLj"
                        },
                        new
                        {
                            Id = 4,
                            Equipment = "dumbbell",
                            ExerciseType = "chest",
                            ImageUrl = "https://i.pinimg.com/736x/ba/0d/37/ba0d37033b6e339039b15d551d294641.jpg",
                            IsDeleted = false,
                            Name = "Chest Fly",
                            TargetMuscles = "chest",
                            VideoUrl = "https://youtu.be/eozdVDA78K0?si=1J1_PyoBVtu_Jwvp"
                        },
                        new
                        {
                            Id = 5,
                            Equipment = "cable",
                            ExerciseType = "chest",
                            ImageUrl = "https://i.pinimg.com/736x/bd/d0/8c/bdd08cc009b9e4a4bc9c4d59ff686689.jpg",
                            IsDeleted = false,
                            Name = "Cable Crossover",
                            TargetMuscles = "chest",
                            VideoUrl = "https://youtu.be/taI4XduLpTk?si=Q62_28A41GTPWvCl"
                        },
                        new
                        {
                            Id = 6,
                            Equipment = "body_weight",
                            ExerciseType = "chest",
                            ImageUrl = "https://i.pinimg.com/1200x/4c/a0/cf/4ca0cf8fba6abc54ff11f3d42f7d4d9d.jpg",
                            IsDeleted = false,
                            Name = "Push Up",
                            TargetMuscles = "chest",
                            VideoUrl = "https://youtu.be/WDIpL0pjun0?si=lyJuGjugdPChmFVf"
                        },
                        new
                        {
                            Id = 7,
                            Equipment = "machine",
                            ExerciseType = "chest",
                            ImageUrl = "https://i.pinimg.com/736x/5a/d5/6d/5ad56d47c0d43c0accea1db38b5fd411.jpg",
                            IsDeleted = false,
                            Name = "Machine Press",
                            TargetMuscles = "chest",
                            VideoUrl = "https://youtube.com/shorts/UH6y0fhbw8w?si=S2ZFGTMcNjDxAOUq"
                        },
                        new
                        {
                            Id = 8,
                            Equipment = "dumbbell",
                            ExerciseType = "chest",
                            ImageUrl = "https://i.pinimg.com/1200x/17/4a/59/174a592203325454f658c920c5b8368d.jpg",
                            IsDeleted = false,
                            Name = "Dumbbell Pullover",
                            TargetMuscles = "chest",
                            VideoUrl = "https://youtu.be/FK4rHfWKEac?si=KwpGQQkVgL3MVpPS"
                        },
                        new
                        {
                            Id = 9,
                            Equipment = "machine",
                            ExerciseType = "chest",
                            ImageUrl = "https://i.pinimg.com/736x/1e/c5/84/1ec5845ed61d3ff2a96bbc678f601c16.jpg",
                            IsDeleted = false,
                            Name = "Incline Machine Press",
                            TargetMuscles = "upper_chest",
                            VideoUrl = "https://youtu.be/VesHgJR14E8?si=0N4-gp9iKJD0Z_fc"
                        },
                        new
                        {
                            Id = 10,
                            Equipment = "machine",
                            ExerciseType = "chest",
                            ImageUrl = "https://i.pinimg.com/736x/5c/25/79/5c257945695e265a496ba6e5119fd6e5.jpg",
                            IsDeleted = false,
                            Name = "Pec Deck Fly",
                            TargetMuscles = "chest",
                            VideoUrl = "https://youtu.be/3jYo5cMU3d4?si=QSQXdXutC4gqwi7z"
                        },
                        new
                        {
                            Id = 11,
                            Equipment = "cable",
                            ExerciseType = "back",
                            ImageUrl = "https://i.pinimg.com/736x/b1/63/1d/b1631da2844586e2c2795e8f7e83918a.jpg",
                            IsDeleted = false,
                            Name = "Lat Pulldown",
                            TargetMuscles = "lats",
                            VideoUrl = "https://youtu.be/AOpi-p0cJkc?si=vdPRoav9ULsi9B74"
                        },
                        new
                        {
                            Id = 12,
                            Equipment = "cable",
                            ExerciseType = "back",
                            ImageUrl = "https://i.pinimg.com/1200x/73/c4/9a/73c49a297f36321216c9b39b46b17a60.jpg",
                            IsDeleted = false,
                            Name = "Seated Row",
                            TargetMuscles = "middle_back",
                            VideoUrl = "https://youtu.be/vwHG9Jfu4sw?si=SvWmWIEXsC_yNIU5"
                        },
                        new
                        {
                            Id = 13,
                            Equipment = "body_weight",
                            ExerciseType = "back",
                            ImageUrl = "https://i.pinimg.com/736x/5c/17/5a/5c175ab10655a9c9990c3ad3b22d6f47.jpg",
                            IsDeleted = false,
                            Name = "Pull Up",
                            TargetMuscles = "lats",
                            VideoUrl = "https://youtube.com/shorts/9rckBLbVe8c?si=-PsQso0hbZ_poD7K"
                        },
                        new
                        {
                            Id = 14,
                            Equipment = "barbell",
                            ExerciseType = "back",
                            ImageUrl = "https://i.pinimg.com/736x/24/b0/f5/24b0f5a32471a84b692054b1a868e0b3.jpg",
                            IsDeleted = false,
                            Name = "Deadlift",
                            TargetMuscles = "lower_back",
                            VideoUrl = "https://youtu.be/PUNxkzCjWNk?si=URLPsaJMweeOfLjI"
                        },
                        new
                        {
                            Id = 15,
                            Equipment = "barbell",
                            ExerciseType = "back",
                            ImageUrl = "https://i.pinimg.com/736x/c3/fa/e1/c3fae1b0cc5da48d1cbff1ce6e7cb9d9.jpg",
                            IsDeleted = false,
                            Name = "T-Bar Row",
                            TargetMuscles = "middle_back",
                            VideoUrl = "https://youtu.be/KDEl3AmZbVE?si=7MiEn6jUuObKoRaQ"
                        },
                        new
                        {
                            Id = 16,
                            Equipment = "dumbbell",
                            ExerciseType = "back",
                            ImageUrl = "https://i.pinimg.com/1200x/29/95/9f/29959f92033e9a64554b25af535e0f2f.jpg",
                            IsDeleted = false,
                            Name = "One Arm Row",
                            TargetMuscles = "lats",
                            VideoUrl = "https://youtu.be/PgpQ4-jHiq4?si=zLMfmyKcHmbDwWd3"
                        },
                        new
                        {
                            Id = 17,
                            Equipment = "cable",
                            ExerciseType = "back",
                            ImageUrl = "https://i.pinimg.com/736x/5e/e6/4e/5ee64e2e9c1ae9b97022107ae16d26ab.jpg",
                            IsDeleted = false,
                            Name = "Straight Arm Pulldown",
                            TargetMuscles = "lats",
                            VideoUrl = "https://youtu.be/wcVDItawocI?si=_eL8xscseTVsKlqD"
                        },
                        new
                        {
                            Id = 18,
                            Equipment = "machine",
                            ExerciseType = "back",
                            ImageUrl = "https://i.pinimg.com/736x/4c/85/d0/4c85d0a72767b66665a97d10612681e6.jpg",
                            IsDeleted = false,
                            Name = "Machine Row",
                            TargetMuscles = "middle_back",
                            VideoUrl = "https://youtu.be/TeFo51Q_Nsc?si=1XKX9L_CSsgJDRh-"
                        },
                        new
                        {
                            Id = 19,
                            Equipment = "barbell",
                            ExerciseType = "back",
                            ImageUrl = "https://i.pinimg.com/736x/fa/52/4b/fa524ba0adc628dbe855033afadba6c2.jpg",
                            IsDeleted = false,
                            Name = "Bent Over Row",
                            TargetMuscles = "middle_back",
                            VideoUrl = "https://youtu.be/-xlBxIMqh3A?si=wmGXzGbvIm9-7bHi"
                        },
                        new
                        {
                            Id = 20,
                            Equipment = "machine",
                            ExerciseType = "back",
                            ImageUrl = "https://i.pinimg.com/736x/60/b7/27/60b7274d9f5b6bd990625b5da40c68db.jpg",
                            IsDeleted = false,
                            Name = "Chest Supported Row",
                            TargetMuscles = "upper_back",
                            VideoUrl = "https://youtu.be/SC_Fg-fbzKQ?si=aDGG7TzdwbMfw73R"
                        },
                        new
                        {
                            Id = 21,
                            Equipment = "barbell",
                            ExerciseType = "biceps",
                            ImageUrl = "https://i.pinimg.com/736x/0e/3d/47/0e3d47c212bd3cf141804f65d07d291b.jpg",
                            IsDeleted = false,
                            Name = "Barbell Curl",
                            TargetMuscles = "biceps",
                            VideoUrl = "https://youtu.be/dDI8ClxRS04?si=vpEn5ec5wnEq3oQT"
                        },
                        new
                        {
                            Id = 22,
                            Equipment = "dumbbell",
                            ExerciseType = "biceps",
                            ImageUrl = "https://i.pinimg.com/736x/2b/80/b8/2b80b84616a9dd930833911c4a663d3c.jpg",
                            IsDeleted = false,
                            Name = "Hammer Curl",
                            TargetMuscles = "biceps",
                            VideoUrl = "https://youtu.be/0IAM2YtviQY?si=IkRA6U3-8vPvZ9V0"
                        },
                        new
                        {
                            Id = 23,
                            Equipment = "barbell",
                            ExerciseType = "biceps",
                            ImageUrl = "https://i.pinimg.com/736x/ed/de/cc/eddecc0ce3200510cce0d549f418e1f9.jpg",
                            IsDeleted = false,
                            Name = "Preacher Curl",
                            TargetMuscles = "biceps",
                            VideoUrl = "https://youtu.be/Gydpcouclx8?si=JgpylBbSDlK3OMWe"
                        },
                        new
                        {
                            Id = 24,
                            Equipment = "dumbbell",
                            ExerciseType = "biceps",
                            ImageUrl = "https://i.pinimg.com/736x/e3/ef/c5/e3efc59257ca9277ac4129cca2c9578b.jpg",
                            IsDeleted = false,
                            Name = "Concentration Curl",
                            TargetMuscles = "biceps",
                            VideoUrl = "https://youtu.be/VMbDQ8PZazY?si=Pgw2IVYimkpdk28k"
                        },
                        new
                        {
                            Id = 25,
                            Equipment = "cable",
                            ExerciseType = "biceps",
                            ImageUrl = "https://i.pinimg.com/1200x/d1/ad/5e/d1ad5e7d75eabcf979160e9ec3a059f1.jpg",
                            IsDeleted = false,
                            Name = "Cable Curl",
                            TargetMuscles = "biceps",
                            VideoUrl = "https://youtube.com/shorts/CrbTqNOlFgE?si=gbrpMjWOYRpDc1tW"
                        },
                        new
                        {
                            Id = 26,
                            Equipment = "dumbbell",
                            ExerciseType = "biceps",
                            ImageUrl = "https://i.pinimg.com/736x/20/e2/7b/20e27b64fadf79ae83c878601df60ffd.jpg",
                            IsDeleted = false,
                            Name = "Spider Curl",
                            TargetMuscles = "biceps",
                            VideoUrl = "https://youtu.be/nvufDW-MSQk?si=_dc4RvTzpjC_rnZe"
                        },
                        new
                        {
                            Id = 31,
                            Equipment = "cable",
                            ExerciseType = "triceps",
                            ImageUrl = "https://i.pinimg.com/736x/39/63/cb/3963cbd3fca0d2623746f53fddee27c9.jpg",
                            IsDeleted = false,
                            Name = "Tricep Pushdown",
                            TargetMuscles = "triceps",
                            VideoUrl = "https://youtu.be/-zLyUAo1gMw?si=yAKXcRkUzyZ_vZBo"
                        },
                        new
                        {
                            Id = 32,
                            Equipment = "dumbbell",
                            ExerciseType = "triceps",
                            ImageUrl = "https://i.pinimg.com/1200x/e7/f1/1c/e7f11c9b787bd83c48b9f7136397cec4.jpg",
                            IsDeleted = false,
                            Name = "Overhead Extension",
                            TargetMuscles = "triceps",
                            VideoUrl = "https://youtu.be/F3w6m0aENVQ?si=XbaI-UQKG3WwZ9kF"
                        },
                        new
                        {
                            Id = 33,
                            Equipment = "body_weight",
                            ExerciseType = "triceps",
                            ImageUrl = "https://i.pinimg.com/736x/36/a7/86/36a786ad24672159f8797d1ad52905b5.jpg",
                            IsDeleted = false,
                            Name = "Bench Dips",
                            TargetMuscles = "triceps",
                            VideoUrl = "https://youtu.be/5XkOdAtPn2Y?si=bdW6PS4GeQyYV1B_"
                        },
                        new
                        {
                            Id = 34,
                            Equipment = "barbell",
                            ExerciseType = "triceps",
                            ImageUrl = "https://i.pinimg.com/736x/13/e7/69/13e769d0001345d8ceadae2867286fb7.jpg",
                            IsDeleted = false,
                            Name = "Skull Crusher",
                            TargetMuscles = "triceps",
                            VideoUrl = "https://youtu.be/l3rHYPtMUo8?si=RYEpLy7eldsGnbDK"
                        },
                        new
                        {
                            Id = 35,
                            Equipment = "barbell",
                            ExerciseType = "triceps",
                            ImageUrl = "https://i.pinimg.com/736x/25/d3/f0/25d3f0a34ddf948fc47f7c5d1dcd43f2.jpg",
                            IsDeleted = false,
                            Name = "Close Grip Bench",
                            TargetMuscles = "triceps",
                            VideoUrl = "https://youtu.be/8o7jud9YlHU?si=dvZbVaKhVEic99OU"
                        },
                        new
                        {
                            Id = 41,
                            Equipment = "barbell",
                            ExerciseType = "forearms",
                            ImageUrl = "https://i.pinimg.com/736x/5a/92/db/5a92db6bc9a75af5f8625aeff4e57c6d.jpg",
                            IsDeleted = false,
                            Name = "Wrist Curl",
                            TargetMuscles = "forearms",
                            VideoUrl = "https://youtu.be/k6F6ugHyTcA?si=BY15MzTrO-ptiB4N"
                        },
                        new
                        {
                            Id = 42,
                            Equipment = "dumbbell",
                            ExerciseType = "forearms",
                            ImageUrl = "https://i.pinimg.com/736x/2c/9f/c0/2c9fc0eab9d24737325d3362e2686f18.jpg",
                            IsDeleted = false,
                            Name = "Reverse Wrist Curl",
                            TargetMuscles = "forearms",
                            VideoUrl = "https://youtu.be/osYPwlBiCRM?si=625NkFc9uH-Wdar_"
                        },
                        new
                        {
                            Id = 43,
                            Equipment = "dumbbell",
                            ExerciseType = "forearms",
                            ImageUrl = "https://i.pinimg.com/736x/2b/80/b8/2b80b84616a9dd930833911c4a663d3c.jpg",
                            IsDeleted = false,
                            Name = "Hammer Curl (Forearms)",
                            TargetMuscles = "brachioradialis",
                            VideoUrl = "https://youtu.be/-ncVKmrtXaM?si=MJal9zMKF7C8blK5"
                        },
                        new
                        {
                            Id = 51,
                            Equipment = "dumbbell",
                            ExerciseType = "shoulders",
                            ImageUrl = "https://i.pinimg.com/736x/3a/33/c4/3a33c4e64884f1c5fafe8217c6e563b5.jpg",
                            IsDeleted = false,
                            Name = "Lateral Raise",
                            TargetMuscles = "side_delts",
                            VideoUrl = "https://youtu.be/PzsMitRdI_8?si=jJKLyqNI3kiISGRc"
                        },
                        new
                        {
                            Id = 52,
                            Equipment = "dumbbell",
                            ExerciseType = "shoulders",
                            ImageUrl = "https://i.pinimg.com/736x/95/83/0a/95830a2bf856831607d5f3749aa1d50a.jpg",
                            IsDeleted = false,
                            Name = "Front Raise",
                            TargetMuscles = "front_delts",
                            VideoUrl = "https://youtu.be/ugPIPY7j-GM?si=9CdRWnFdQ3uwv0Xw"
                        },
                        new
                        {
                            Id = 53,
                            Equipment = "dumbbell",
                            ExerciseType = "shoulders",
                            ImageUrl = "https://i.pinimg.com/736x/9a/bb/6c/9abb6ca4337f7c6eb11438fe0f3f2f35.jpg",
                            IsDeleted = false,
                            Name = "Shoulder Press",
                            TargetMuscles = "shoulders",
                            VideoUrl = "https://youtu.be/0JfYxMRsUCQ?si=lm25qvcCLp-J36pQ"
                        },
                        new
                        {
                            Id = 54,
                            Equipment = "dumbbell",
                            ExerciseType = "shoulders",
                            ImageUrl = "https://i.pinimg.com/736x/a4/14/18/a414187e689e9378d490ea5863682ce5.jpg",
                            IsDeleted = false,
                            Name = "Rear Delt Fly",
                            TargetMuscles = "rear_delts",
                            VideoUrl = "https://youtu.be/nlkF7_2O_Lw?si=3Wqh4ZfJafBRV4n3"
                        },
                        new
                        {
                            Id = 55,
                            Equipment = "barbell",
                            ExerciseType = "shoulders",
                            ImageUrl = "https://i.pinimg.com/1200x/e6/9d/c2/e69dc2fe577505490a8fc4a2830f198e.jpg",
                            IsDeleted = false,
                            Name = "Upright Row",
                            TargetMuscles = "traps",
                            VideoUrl = "https://youtu.be/pNTPVN3FkSo?si=TvV_C0yUBLQfLLPX"
                        },
                        new
                        {
                            Id = 61,
                            Equipment = "barbell",
                            ExerciseType = "legs",
                            ImageUrl = "https://i.pinimg.com/736x/d0/a7/ba/d0a7ba56416b59882350bb7287509f6b.jpg",
                            IsDeleted = false,
                            Name = "Barbell Squat",
                            TargetMuscles = "quadriceps,glutes",
                            VideoUrl = "https://youtu.be/VZ90qWlfQUE?si=LGbTzbAB1HPT1v0P"
                        },
                        new
                        {
                            Id = 62,
                            Equipment = "machine",
                            ExerciseType = "legs",
                            ImageUrl = "https://i.pinimg.com/736x/e0/52/59/e05259675f0a51b47e34832f11658b23.jpg",
                            IsDeleted = false,
                            Name = "Leg Press",
                            TargetMuscles = "quadriceps",
                            VideoUrl = "https://youtu.be/Aq5uxXrXq7c?si=vlpD_LC2NhpNJKzc"
                        },
                        new
                        {
                            Id = 63,
                            Equipment = "barbell",
                            ExerciseType = "legs",
                            ImageUrl = "https://i.pinimg.com/1200x/c4/78/ca/c478ca0a0c2fdfcad460a9d30d8cb644.jpg",
                            IsDeleted = false,
                            Name = "Romanian Deadlift",
                            TargetMuscles = "hamstrings,glutes",
                            VideoUrl = "https://youtu.be/3VXmecChYYM?si=uwqxIG4wLg2jwCIK"
                        },
                        new
                        {
                            Id = 64,
                            Equipment = "dumbbell",
                            ExerciseType = "legs",
                            ImageUrl = "https://i.pinimg.com/736x/ad/fd/58/adfd5843a204ab3edc730f621c9f0a9f.jpg",
                            IsDeleted = false,
                            Name = "Walking Lunge",
                            TargetMuscles = "quadriceps,glutes",
                            VideoUrl = "https://youtu.be/DlhojghkaQ0?si=EfraGrmFD2oefoRS"
                        },
                        new
                        {
                            Id = 65,
                            Equipment = "machine",
                            ExerciseType = "legs",
                            ImageUrl = "https://i.pinimg.com/736x/d6/18/8c/d6188c81ef3c4d531a7d6f089782d3f6.jpg",
                            IsDeleted = false,
                            Name = "Leg Extension",
                            TargetMuscles = "quadriceps",
                            VideoUrl = "https://youtu.be/4ZDm5EbiFI8?si=rHR40-hEN9dsdS8J"
                        },
                        new
                        {
                            Id = 66,
                            Equipment = "machine",
                            ExerciseType = "legs",
                            ImageUrl = "https://i.pinimg.com/736x/df/e6/54/dfe65427b2dee11c036df7c00f5969fc.jpg",
                            IsDeleted = false,
                            Name = "Leg Curl",
                            TargetMuscles = "hamstrings",
                            VideoUrl = "https://youtu.be/t9sTSr-JYSs?si=xgSRknmAPZXRIrl1"
                        },
                        new
                        {
                            Id = 67,
                            Equipment = "dumbbell",
                            ExerciseType = "legs",
                            ImageUrl = "https://i.pinimg.com/736x/c4/82/65/c482650b63f3c5d0c145f529ae1c1c6d.jpg",
                            IsDeleted = false,
                            Name = "Bulgarian Split Squat",
                            TargetMuscles = "quadriceps,glutes",
                            VideoUrl = "https://youtu.be/DeCnHqrN22U?si=NjmILoT3hYh0byTl"
                        },
                        new
                        {
                            Id = 68,
                            Equipment = "barbell",
                            ExerciseType = "legs",
                            ImageUrl = "https://i.pinimg.com/736x/00/c6/9f/00c69f716bf3d49a4d5e2fb99c2a89e4.jpg",
                            IsDeleted = false,
                            Name = "Hip Thrust",
                            TargetMuscles = "glutes",
                            VideoUrl = "https://youtu.be/pUdIL5x0fWg?si=SqXn95gLxd2CR9mn"
                        },
                        new
                        {
                            Id = 69,
                            Equipment = "machine",
                            ExerciseType = "legs",
                            ImageUrl = "https://i.pinimg.com/736x/59/f7/f7/59f7f7a2e2d085f072b38d6d96d93ca4.jpg",
                            IsDeleted = false,
                            Name = "Calf Raise",
                            TargetMuscles = "calves",
                            VideoUrl = "https://youtube.com/shorts/baEXLy09Ncc?si=V2sXkPpE6XYopn0l"
                        });
                });

            modelBuilder.Entity("Ai_Fitness_Coach.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Goal")
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetOtp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetOtpExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VerificationOtp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerificationOtpExpiry")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ai_Fitness_Coach.Models.WorkoutAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("TotalReps")
                        .HasColumnType("int");

                    b.Property<double>("TotalVolume")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("WorkoutAnalyses");
                });

            modelBuilder.Entity("Ai_Fitness_Coach.Models.WorkoutPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutPlans");
                });

            modelBuilder.Entity("Ai_Fitness_Coach.Models.WorkoutPlanExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("WorkoutPlanExercises");
                });

            modelBuilder.Entity("Ai_Fitness_Coach.Models.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkoutPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("Ai_Fitness_Coach.Models.WorkoutSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("WorkoutSets");
                });

            modelBuilder.Entity("ExerciseAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FormScore")
                        .HasColumnType("float");

                    b.Property<int>("RepsDetected")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkoutSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("ExerciseAnalyses");
                });

            modelBuilder.Entity("Ai_Fitness_Coach.Models.WorkoutAnalysis", b =>
                {
                    b.HasOne("Ai_Fitness_Coach.Models.WorkoutSession", "WorkoutSession")
                        .WithOne("WorkoutAnalysis")
                        .HasForeignKey("Ai_Fitness_Coach.Models.WorkoutAnalysis", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("Ai_Fitness_Coach.Models.WorkoutPlan", b =>
                {
                    b.HasOne("Ai_Fitness_Coach.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ai_Fitness_Coach.Models.WorkoutPlanExercise", b =>
                {
                    b.HasOne("Ai_Fitness_Coach.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ai_Fitness_Coach.Models.WorkoutPlan", "WorkoutPlan")
                        .WithMany("PlanExercises")
                        .HasForeignKey("WorkoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("Ai_Fitness_Coach.Models.WorkoutSession", b =>
                {
                    b.HasOne("Ai_Fitness_Coach.Models.User", "User")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ai_Fitness_Coach.Models.WorkoutPlan", "WorkoutPlan")
                        .WithMany("Sessions")
                        .HasForeignKey("WorkoutPlanId");

                    b.Navigation("User");

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("Ai_Fitness_Coach.Models.WorkoutSet", b =>
                {
                    b.HasOne("Ai_Fitness_Coach.Models.Exercise", "Exercise")
                        .WithMany("WorkoutSets")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ai_Fitness_Coach.Models.WorkoutSession", "WorkoutSession")
                        .WithMany("WorkoutSets")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("ExerciseAnalysis", b =>
                {
                    b.HasOne("Ai_Fitness_Coach.Models.Exercise", "Exercise")
                        .WithMany("ExerciseAnalyses")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ai_Fitness_Coach.Models.User", "User")
                        .WithMany("ExerciseAnalyses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ai_Fitness_Coach.Models.WorkoutSession", "WorkoutSession")
                        .WithMany("ExerciseAnalyses")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Exercise");

                    b.Navigation("User");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("Ai_Fitness_Coach.Models.Exercise", b =>
                {
                    b.Navigation("ExerciseAnalyses");

                    b.Navigation("WorkoutSets");
                });

            modelBuilder.Entity("Ai_Fitness_Coach.Models.User", b =>
                {
                    b.Navigation("ExerciseAnalyses");

                    b.Navigation("WorkoutSessions");
                });

            modelBuilder.Entity("Ai_Fitness_Coach.Models.WorkoutPlan", b =>
                {
                    b.Navigation("PlanExercises");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Ai_Fitness_Coach.Models.WorkoutSession", b =>
                {
                    b.Navigation("ExerciseAnalyses");

                    b.Navigation("WorkoutAnalysis");

                    b.Navigation("WorkoutSets");
                });
#pragma warning restore 612, 618
        }
    }
}
